spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tasklib
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: create
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html